[package]
name = "thirtyfour-mouse"
version = "0.2.0"
edition = "2024"
description = "Manipulate mouse movements with ThirtyFour"
repository = "https://github.com/0xlunar/thirtyfour-mouse"
license = "GPL-3.0"

[dependencies]
enterpolation = "0.3.0"
rand = { version = "0.10.0-rc.0", features = [] }
thirtyfour = { version = "0.36.1" }
async-trait = "0.1.89"