[package]
name = "thirtyfour-mouse"
version = "0.1.0"
edition = "2021"

[dependencies]
enterpolation = "0.2.1"
rand = { version = "0.8.5", features = [] }
thirtyfour = { git = "https://github.com/0xlunar/thirtyfour.git", branch = "custom-delay-action-chains" }
async-trait = "0.1.83"
